console.log("Gracias")
console.log("Thank you")
console.log("Merci")
console.log("Gràcies")
console.log("ありがとうございました")
console.log("고맙습니다")
console.log("Vielen Dank")
console.log("Grazie")
console.log("谢谢")
console.log("Спасибо ")