console.log("Gracias  //  Español")
console.log("Thank you // Inglés")
console.log("Merci // Francés")
console.log("Gràcies // Catalán")
console.log("ありがとうございました // Japonés")
console.log("고맙습니다 // Coreano")
console.log("Vielen Dank // Alemán")
console.log("Grazie // Italiano")
console.log("谢谢 // Chino")
console.log("Спасибо // Ruso")